# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VietVetVect
                                 A QGIS plugin
 This plugin helps the evaluation of vector-borne infection data from a Vietnamian survey.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-27
        copyright            : (C) 2024 by Norbert Solymosi
        email                : solymosi.norbert@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VietVetVect class from file VietVetVect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .viet_vet_vect import VietVetVect
    return VietVetVect(iface)
