# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VietVetVect
                                 A QGIS plugin
 This plugin helps the evaluation of vector-borne infection data from a Vietnamian survey.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Norbert Solymosi
        email                : solymosi.norbert@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject
from qgis.core import QgsFeature
from qgis.core import Qgis
from qgis.core import QgsApplication
from qgis.core import QgsVectorLayer
from qgis.core import QgsCoordinateReferenceSystem
from qgis.core import QgsCoordinateTransform
from qgis.core import QgsCoordinateTransformContext
from qgis.utils import OverrideCursor
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QFileDialog
import webbrowser

# from qgis.PyQt import QtGui
# import pandas as pd

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .viet_vet_vect_dialog import VietVetVectDialog
from .sp_query_dlg import spQuery_dlg
from .clim_proj_dlg import climProj_dlg
import os.path


class VietVetVect:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VietVetVect_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&VietVetVect')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VietVetVect', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # icon_path = ':/plugins/viet_vet_vect/icon.png'
        self.add_action(
            ':/plugins/viet_vet_vect/mActionCircleExtent.svg',
            text=self.tr(u'Buffering'),
            callback=self.buffering,
            parent=self.iface.mainWindow())
        
        self.add_action(
            ':/plugins/viet_vet_vect/mIconBrowserRelations.svg',
            text=self.tr(u'Spatial query'),
            callback=self.spquery,
            parent=self.iface.mainWindow())        
        
        self.add_action(
            ':/plugins/viet_vet_vect/mActionDecreaseBrightness.svg',
            text=self.tr(u'Load climate projection layer'),
            callback=self.climproj,
            parent=self.iface.mainWindow())    

        self.add_action(
            ':/plugins/viet_vet_vect/metadata.svg',
            text=self.tr(u'Help'),
            callback=self.help,
            parent=self.iface.mainWindow())                      

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&VietVetVect'),
                action)
            self.iface.removeToolBarIcon(action)

    def help(self):
        webbrowser.open('https://raw.githubusercontent.com/solymosin/index/master/pages/vietvetvect.html')
        # https://raw.githubusercontent.com/solymosin/index/master/pages/vietvetvect.html
        # pass

    def climproj(self):
        # if self.first_start == True:
        #     self.first_start = False
        self.dlg = climProj_dlg()
        
        self.dlg.setWindowTitle("Load climate projection layer")

        self.dlg.comboBox.clear()
        self.dlg.comboBox.addItems(["ACCESS-CM2", "CMCC-ESM2", "EC-Earth3-Veg", "GISS-E2-1-G", "INM-CM5-0", "IPSL-CM6A-LR", "MIROC6", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL"])
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_2.addItems(['ssp126','ssp245','ssp370','ssp585'])  
        self.dlg.comboBox_3.clear()
        self.dlg.comboBox_3.addItems(['2041-2060','2061-2080'])          

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:    
            with OverrideCursor(Qt.WaitCursor): 
                ln = self.dlg.comboBox.currentText() + '_' + self.dlg.comboBox_2.currentText() + '_' + self.dlg.comboBox_3.currentText() 
                fld = os.path.dirname(os.path.abspath(__file__))
                pth = os.path.join(fld, 'maps/wc2.1_10m_bioc_' + ln + '.shp')   
                # self.iface.messageBar().pushMessage("Success", pth, level=Qgis.Success, duration=3)
    
                vlayer = QgsVectorLayer(pth, ln, "ogr")
                if not vlayer.isValid():
                    print("Layer failed to load!")
                else:
                    QgsProject.instance().addMapLayer(vlayer)
                # pass

    def getFldsbyqLyr(self):
        # model = QtGui.QStandardItemModel()
        # self.dlg.listView.setModel(model)        
        self.dlg.listWidget.clear()
        lyr = QgsProject.instance().mapLayersByName(self.dlg.comboBox.currentText())[0]
        fields = lyr.fields()   
        for field in fields:        
            self.dlg.listWidget.addItem(field.name())
            # item = QtGui.QStandardItem(field.name())
            # model.appendRow(item)
        
    def getFldsbysLyr(self):
        # model = QtGui.QStandardItemModel()
        # self.dlg.listView_2.setModel(model)          
        self.dlg.listWidget_2.clear()             
        lyr = QgsProject.instance().mapLayersByName(self.dlg.comboBox_2.currentText())[0]
        fields = lyr.fields()   
        for field in fields:      
            self.dlg.listWidget_2.addItem(field.name())  
            # item = QtGui.QStandardItem(field.name())
            # model.appendRow(item)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.csv')
        self.dlg.lineEdit.setText(filename)

    def spquery(self):
        # if self.first_start == True:
        #     self.first_start = False
        self.dlg = spQuery_dlg()
        
        self.dlg.setWindowTitle("Simple spatial query")
        layers = QgsProject.instance().layerTreeRoot().children()
        self.dlg.toolButton.clicked.connect(self.select_output_file)
        self.dlg.comboBox.currentTextChanged.connect(self.getFldsbyqLyr)
        self.dlg.comboBox_2.currentTextChanged.connect(self.getFldsbysLyr)      
        
        self.dlg.comboBox.clear()
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_2.addItems([layer.name() for layer in layers])
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:     
            fldas = []        
            for item in self.dlg.listWidget.selectedItems():
                fldas.append(item.text())
            fldbs = []        
            for item in self.dlg.listWidget_2.selectedItems():
                fldbs.append(item.text())                

            with OverrideCursor(Qt.WaitCursor):     
                filename = self.dlg.lineEdit.text()
                with open(filename, 'w') as output_file:
                    line = ""
                    for flda in fldas:
                        line += flda + "; "                                                      
                    for fldb in fldbs:
                        line += fldb + "; " 
                    output_file.write(line + "\n")

                lyra = QgsProject.instance().mapLayersByName(self.dlg.comboBox.currentText())[0]
                lyrb = QgsProject.instance().mapLayersByName(self.dlg.comboBox_2.currentText())[0]
                trafo = QgsCoordinateTransform(lyra.crs(), lyrb.crs(), QgsCoordinateTransformContext())
                for fa in lyra.getFeatures():
                    ga = fa.geometry()
                    ga.transform(trafo)
                    for fb in lyrb.getFeatures():
                        gb = fb.geometry()
                        if ga.intersects(gb):  
                            line = ""
                            for flda in fldas:
                                line += str(fa.attribute(flda)) + "; "                                                      
                            for fldb in fldbs:
                                line += str(fb.attribute(fldb)) + "; "            
                            with open(filename, 'a') as output_file:
                                output_file.write(line + "\n")

                self.iface.messageBar().pushMessage("Success", "Output file written at " + filename, level=Qgis.Success, duration=3)


    def buffering(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        # if self.first_start == True:
        #     self.first_start = False
        self.dlg = VietVetVectDialog()

        self.dlg.setWindowTitle("Generate buffers around features")
        layers = QgsProject.instance().layerTreeRoot().children()
        self.dlg.comboBox.clear()
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.spinBox.setValue(10)
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.              
            with OverrideCursor(Qt.WaitCursor):     
                srcLayer = QgsProject.instance().mapLayersByName(self.dlg.comboBox.currentText())[0]
                trafo = QgsCoordinateTransform(srcLayer.crs(), QgsCoordinateReferenceSystem(3857), QgsCoordinateTransformContext())
                dstLayer = QgsVectorLayer('Polygon?crs=EPSG:3857', 'buffers_'+str(self.dlg.spinBox.value())+'_km_radius', 'memory')   
                dstLayer.startEditing()        
                fields = srcLayer.fields()   
                for field in fields:
                    dstLayer.addAttribute(field)   

                for feature in srcLayer.getFeatures():
                    g = feature.geometry()
                    g.transform(trafo)
                    b = g.buffer(self.dlg.spinBox.value()*1000, 50)
                    f = QgsFeature(dstLayer.fields())
                    for index, field in enumerate(srcLayer.fields()):
                        f.setAttribute(index, feature.attribute(field.name()))                    
                    f.setGeometry(b)      
                    dstLayer.addFeature(f)
                dstLayer.commitChanges()
                QgsProject.instance().addMapLayer(dstLayer)  

                # crsSrc = QgsCoordinateReferenceSystem(4326)
                # crsDest = QgsCoordinateReferenceSystem(3857)
                # trafo1 = QgsCoordinateTransform(crsSrc, crsDest)
                # transform = QgsCoordinateTransform(crsSrc, crsDest, QgsCoordinateTransformContext())            
                #selidx = self.dlg.comboBox.currentIndex()                   
                #self.iface.setActiveLayer(layers[selidx].layer())
                # srcLayer = QgsProject.instance().mapLayersByName(self.dlg.comboBox.currentText())[0]
                # self.iface.setActiveLayer(al)
                # srcLayer = self.iface.activeLayer()
                # trafo = QgsCoordinateTransform(srcLayer.crs(), QgsCoordinateReferenceSystem(3857), QgsCoordinateTransformContext())
                # self.iface.messageBar().pushMessage("Info", "Layer index: " + str(srcLayer.crs().authid()), level=Qgis.Info)
                # dstLayer = QgsVectorLayer("Polygon", "buffer", "memory")
                # dstLayer = QgsVectorLayer('Polygon?crs=EPSG:4326', 'buffer', 'memory')
                # dstLayer = QgsVectorLayer('Polygon?crs=EPSG:3857', 'buffers_'+str(self.dlg.spinBox.value())+'_km_radius', 'memory')   
                # https://gis.stackexchange.com/questions/351156/copying-attribute-values-to-new-layer-in-qgis-with-python
                # pr = dstLayer.dataProvider()
                # dstLayer.addAttributes(srcLayer.fields())
                # dstLayer.updateFields()    
                # dstLayer.startEditing()                                
                # for feature in srcLayer.getFeatures():
                    # geom = feature.geometry()
                    # buffer = geom.buffer(0.1, 50)
                    # feat = QgsFeature()
                    # feat.setGeometry(buffer)                
                    # g = feature.geometry()
                    # g.transform(trafo)
                    # b = g.buffer(self.dlg.spinBox.value()*1000, 50)
                    # f = QgsFeature()
                    # f.setGeometry(b)      
                    # f.setAttributes(feature.attributes())
                    # g = f.geometry()
                    # g.transform(transform)
                    # b = geom.buffer(10000, 50)                                
                #     dstLayer.addFeature(f)
                # dstLayer.commitChanges()
                # QgsProject.instance().addMapLayer(dstLayer)           
                # dstLayer = QgsVectorLayer('Polygon?crs=EPSG:3857', 'buffer', 'memory')
                # dstLayer.startEditing()
                # for feature in srcLayer.getFeatures():
                #     geom = feature.geometry()
                #     geom.transform(trafo1)
                #     buffer = geom.buffer(1000, 50)
                #     feat = QgsFeature()
                #     feat.setGeometry(buffer)
                #     self.iface.messageBar().pushMessage("Info", "Layer index: " + feat.geometry().asWkt() , level=Qgis.Info)
                #     dstLayer.addFeature(feat)
                # dstLayer.commitChanges()
                # QgsProject.instance().addMapLayer(dstLayer)
                #pass


